####
GET http://localhost:3000/api/members

####
GET http://localhost:3000/api/members?team=marketing

####
GET http://localhost:3000/api/members?team=engineering

####
GET http://localhost:3000/api/members/12344

####
GET http://localhost:3000/api/members/10

####
GET http://localhost:3000/api/members/2

###
POST http://localhost:3000/api/members
Content-Type: application/json

{
    # "id": 12,
    "name": "William",
    "team":"engineering",
    "position":"Android Developer",
    "emailAddress":"zake@developer.com",
    "phoneNumber":"010-xxxx-xxxx",
    "admissionDate":"2021/06/12",
    "birthday":"1995/09/27",
    "profileImage":"profile11.png"

}

###
PUT http://localhost:3000/api/members/1
Content-Type: application/json

{

    "position": "Server Developer"
}