####
GET http://localhost:3000/api/members

####
GET http://localhost:3000/api/members?team=marketing

####
GET http://localhost:3000/api/members?team=engineering

####
GET http://localhost:3000/api/members/12344

####
GET http://localhost:3000/api/members/10

####
GET http://localhost:3000/api/members/2

###
POST http://localhost:3000/api/members
Content-Type: application/json

{
    # "id": 12,
    "name": "William",
    "team":"engineering",
    "position":"Android Developer",
    "emailAddress":"zake@developer.com",
    "phoneNumber":"010-xxxx-xxxx",
    "admissionDate":"2021/06/12",
    "birthday":"1995/09/27",
    "profileImage":"profile11.png"

}

###
PUT http://localhost:3000/api/members/1
Content-Type: application/json

{
#     "id": 1,
#     "name": "Alex",
#     "team": "engineering",
    "position": "Server Developer"
    # "emailAddress": "alex@google.com",
    # "phoneNumber": "010-xxxx-xxxx",
    # "admissionDate": "2018-12-10T00:00:00.000Z",
    # "birthday": "1994-11-08T00:00:00.000Z",
    # "profileImage": "profile1.png",
    # "createdAt": "2023-04-29T03:18:32.000Z",
    # "updatedAt": "2023-04-29T03:18:32.000Z"
    
}